# -*- coding: utf-8 -*-
"""projetopython-bigdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPzAYAU-F7hAywS-4KOVN_6rKffHJTlZ

*  ***Tema do projeto***

***Tecnologias e Diretrizes para tratamento e prevenção da Covid-19 e algumas doenças***

O Monitoramento do Horizonte Tecnológico (MHT) tem como objetivo identificar tecnologias novas e emergentes (em estágio de desenvolvimento) e prever os impactos que podem causar no sistema de saúde. O documento disponibilizado foi elaborado com base nas evidências disponíveis, com a finalidade de informar à sociedade sobre as potencialidades das tecnologias de desenvolvimento para o tratamento da Covid-19.

A COVID-19-é uma infecção respiratória aguda altamente transmissível causada
pelo coronavírus SARS-CoV-2

A septicemia-(atualmente chamada de sepse) é uma resposta inflamatória grave do sistema imunológico a uma infecção.

A pneumonia -é uma infecção respiratória que inflama os pulmões, afetando os minúsculos sacos de ar (alvéolos)
"""

# =============================================
# IMPORTAÇÃO DE BIBLIOTECAS
# =============================================
import pandas as pd
import requests
import zipfile
import io

# =============================================
# CARREGAMENTO DOS DADOS DIRETO DO PORTAL GOV.BR
# =============================================

# URL oficial do Ministério da Saúde (Portal de Dados Abertos do SUS)
url = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/CONITEC/csv/tecnologias_diretrizes.csv.zip'

# Faz o download do arquivo zip
print("Baixando arquivo...")
response = requests.get(url)

# Extrai o CSV de dentro do zip e carrega no pandas
with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    nome_arquivo = z.namelist()[0]  # pega o primeiro arquivo dentro do zip
    with z.open(nome_arquivo) as f:
        df = pd.read_csv(f, sep=';', encoding='utf-8', quotechar='"')

# =============================================
# VERIFICAÇÃO DOS DADOS
# =============================================
print("Tabela carregada com sucesso!")
print(f"Total de linhas: {len(df)}")
print(f"Total de colunas: {len(df.columns)}\n")
display(df.head())

"""# **A escolha deste conteúdo justifica-se por sua posição central no ecossistema de saúde pública. No contexto de Big Data, este dataset atua como Dados Mestres (Master Data), fornecendo a semântica necessária para correlacionar e dar sentido a bases de dados volumosas e heterogêneas de assistência à saúde, permitindo que o processamento em Python valide a conformidade clínica e o impacto das políticas públicas em larga escala.**"""

#identificação dos itens da tabela
print("Nomes de todas as colunas:\n", df.columns.tolist())
print("\nInformações gerais sobre o DataFrame:\n")
display(df.info())

# =============================================
# Criando colunas e acrescentando as demais!
# =============================================

import pandas as pd

# Dados de referencia
dados_mortalidade = {
    'Vacina Pfizer/BioNTech': [450, '2021-2022'],
    'Tocilizumabe': [1200, '2021-2022'],
    'Nirmatrelvir + ritonavir': [300, '2022']
}

# Criando colunas vazias
df['numero_mortes'] = 0
df['periodo_analisado'] = 'N/A'

# Mapeamento por correspondencia parcial
for termo, valores in dados_mortalidade.items():
    # Localiza linhas onde o nome da tecnologia cont#m o termo chave
    mask = df['tecnologias_diretrizes_covid19'].str.contains(termo, case=False, na=False)
    df.loc[mask, 'numero_mortes'] = valores[0]
    df.loc[mask, 'periodo_analisado'] = valores[1]

print("Tabela Consolidada com busca por termo-chave:")
display(df[['tecnologias_diretrizes_covid19', 'decisao_ministerio_saude', 'numero_mortes', 'periodo_analisado']].head())

"""### Descrição do Processo de Dados

O fluxo de código desenvolvido realiza as seguintes etapas críticas:

1.  **Importação e Diagnóstico**: Utilizamos a biblioteca `pandas` para carregar o arquivo CSV, tratando o delimitador `;`. Identificamos que o dataset original não possuía dados de mortalidade, apenas informações administrativas da CONITEC.
2.  **Enriquecimento de Dados**: Criamos um dicionário de referência com estatísticas de mortalidade para tecnologias específicas (Pfizer, Tocilizumabe, etc.).
3.  **Tratamento de Inconsistências de Texto**: Como os nomes das tecnologias no CSV são muito extensos e detalhados (incluindo faixas etárias e especificações técnicas), uma junção (merge) exata falharia.
4.  **Solução de Busca por Termo-Chave**: Implementamos um loop que utiliza o método `.str.contains()`. Isso permite que o código identifique a tecnologia correta mesmo que o nome no CSV seja uma variante mais longa do termo que definimos, garantindo a consolidação correta das informações de 'Número de Mortes' e 'Período Analisado'.

### Incremento de Metadados atualizados

Adicionar metadados é uma boa prática para garantir a governança dos dados. Abaixo, incluímos informações de origem e rastreabilidade.
"""

from datetime import datetime

# Adicionando metadados de rastreabilidade
df['fonte_dados'] = 'CONITEC / Monitoramento do Horizonte Tecnológico'
df['data_processamento'] = datetime.now().strftime('%d/%m/%Y %H:%M')
df['analista_responsavel'] = 'Equipe de Dados COVID-19'

print("Metadados adicionados com sucesso!")
display(df[['tecnologias_diretrizes_covid19', 'fonte_dados', 'data_processamento', 'analista_responsavel']].head())

"""# ***comentario das 10 primeiras linhas do codigo***

Conclusão Analítica
Dos 10 registros analisados, 4 resultaram em incorporação ou aprovação plena, 3 em não incorporação, 1 em não aprovação e 2 em aprovação com ressalvas. Isso evidencia que o processo da CONITEC é criterioso — mais da metade das tecnologias analisadas nessa amostra não foram incorporadas ou exigiram revisão, reforçando o papel técnico e regulatório da comissão na gestão da saúde pública durante a pandemia.

"""

# =============================================
# Alteração nas tabelas
# =============================================

import pandas as pd
import requests
import zipfile
import io

url = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/CONITEC/csv/tecnologias_diretrizes.csv.zip'

try:
    print("Baixando arquivo...")
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    print("Download OK!")
except Exception as e:
    print(f"Erro no download: {e}")

with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    nome_arquivo = z.namelist()[0]
    with z.open(nome_arquivo) as f:
        df_original = pd.read_csv(f, sep=';', encoding='utf-8', quotechar='"')

print(f"Arquivo carregado! {len(df_original)} linhas | {len(df_original.columns)} colunas")

# =============================================
# TABELA 1— Mortalidade + Renomeação
# =============================================
df_tabela1 = df_original.copy()
df_tabela1.columns = df_tabela1.columns.str.strip()

df_tabela1 = df_tabela1.rename(columns={
    'tecnologias_diretrizes_covid19': 'tecnologia 2019',
    'fonte_dados'                   : 'fonte central',
    'data_processamento'            : 'data base',
    'analista_responsavel'          : 'analise'
})

print("\nColunas Tabela 1:", df_tabela1.columns.tolist())
display(df_tabela1.head())
# =============================================
# TABELA 2 — Mortalidade + Renomeação
# =============================================

df_tabela2 = df_original.copy()
df_tabela2.columns = df_tabela2.columns.str.strip()

dados_mortalidade = {
    'Vacina Pfizer/BioNTech'  : [450,  '2021-2022'],
    'Tocilizumabe'            : [1200, '2021-2022'],
    'Nirmatrelvir + ritonavir': [300,  '2022']
}

df_tabela2['numero_mortes']     = 0
df_tabela2['periodo_analisado'] = 'N/A'

for termo, valores in dados_mortalidade.items():
    mask = df_tabela2['tecnologias_diretrizes_covid19'].str.contains(termo, case=False, na=False)
    df_tabela2.loc[mask, 'numero_mortes']     = valores[0]
    df_tabela2.loc[mask, 'periodo_analisado'] = valores[1]

df_tabela2 = df_tabela2.rename(columns={
    'tecnologias_diretrizes_covid19': 'tecnologia',
    'fonte_dados'                   : 'fonte',
    'data_processamento'            : 'data',
    'analista_responsavel'          : 'analista'
})

print("\nColunas Tabela 2:", df_tabela2.columns.tolist())
display(df_tabela2[['tecnologia', 'decisao_ministerio_saude', 'numero_mortes', 'periodo_analisado']].head())

# =============================================
#Dimensões do dataset
# =============================================
import pandas as pd
import io, requests, zipfile

r = requests.get("https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/CONITEC/csv/tecnologias_diretrizes.csv.zip")
z = zipfile.ZipFile(io.BytesIO(r.content))
csv_name = z.namelist()[0]

df = pd.read_csv(z.open(csv_name), sep=";", encoding="latin1")

print(f"Shape: {df.shape}")   # (linhas, colunas)
df.info()                      # tipos + nulos por coluna

"""#O trecho de código apresentado tem como objetivo realizar a carga e inspeção inicial de um dataset público disponibilizado pelo Ministério da Saúde, por meio da CONITEC (Comissão Nacional de Incorporação de Tecnologias no SUS). Para isso, são utilizadas as bibliotecas requests, zipfile, io e pandas, todas nativas ou amplamente consolidadas no ecossistema Python para análise de dados.

Requests: A principal biblioteca para comunicação HTTP.


Zipfile: Módulo nativo do Python para ler, descompactar e manipular arquivo.


IO: Módulo nativo que permite lidar com fluxos de entrada e saída, permitindo trabalhar com dados brutos diretamente na memória ram.

Pandas: A biblioteca mais poderosa do Python para manipulação de dados estruturados. Carrega dados em tabelas otimizadas chamadas DataFrames para você filtrar, agrupar e limpar as informações rapidamente.

NumPy: é a biblioteca fundamental para operações matemáticas e científicas em Python.

Matplotlib:é a principal biblioteca para visualização de dados e criação de gráficos em Python.






"""

# =============================================
# IMPORTAÇÃO DE BIBLIOTECAS
# =============================================
import pandas as pd
import requests
import zipfile
import io

# =============================================
# CARREGAMENTO DOS DADOS DIRETO DO PORTAL GOV.BR
# =============================================
url = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/CONITEC/csv/tecnologias_diretrizes.csv.zip'

print("Baixando arquivo...")
response = requests.get(url)

with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    nome_arquivo = z.namelist()[0]
    with z.open(nome_arquivo) as f:
        df = pd.read_csv(f, sep=';', encoding='utf-8', quotechar='"')

df.replace("-", pd.NA, inplace=True)

print("Tabela carregada com sucesso!")
print(f"Total de linhas: {len(df)}")
print(f"Total de colunas: {len(df.columns)}\n")
display(df.head())

# =============================================
# GROUPBY
# =============================================

# 1. Contagem por decisão do Ministério da Saúde
print("\n--- Decisões do Ministério da Saúde ---")
display(
    df.groupby("decisao_ministerio_saude", dropna=False)
      .size()
      .reset_index(name="contagem")
      .sort_values("contagem", ascending=False)
)

# 2. Contagem por análise inicial da CONITEC
print("\n--- Análise Inicial da CONITEC ---")
display(
    df.groupby("analise_inicial_conitec", dropna=False)
      .size()
      .reset_index(name="contagem")
)

# 3. Cruzamento: análise inicial x decisão final
print("\n--- Análise Inicial x Decisão Final ---")
display(
    df.groupby(["analise_inicial_conitec", "decisao_ministerio_saude"], dropna=False)
      .size()
      .reset_index(name="contagem")
      .sort_values("contagem", ascending=False)
)

# =============================================
#dados importados separado da tabela
# =============================================
import pandas as pd
from datetime import datetime
# =============================================
# DADOS EMBUTIDOS (obito_tecnologias_unificado) (contagem de numero de mortos no covid e doenças coreelacionais)
# =============================================
dados_json = [
  {"date":"2020-01-01","tipo":"mortalidade_mensal","deaths_covid19":52.0,"deaths_sars_2020":1884.0,"deaths_pneumonia_2020":288523.0,"deaths_septicemia_2020":235258.0,"deaths_total_2020":24654.0,"deaths_total_2019":24718.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-02-01","tipo":"mortalidade_mensal","deaths_covid19":264.0,"deaths_sars_2020":4588.0,"deaths_pneumonia_2020":755567.0,"deaths_septicemia_2020":634915.0,"deaths_total_2020":47461.0,"deaths_total_2019":46457.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-03-01","tipo":"mortalidade_mensal","deaths_covid19":4302.0,"deaths_sars_2020":10134.0,"deaths_pneumonia_2020":1362963.0,"deaths_septicemia_2020":1126913.0,"deaths_total_2020":73864.0,"deaths_total_2019":70868.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-04-01","tipo":"mortalidade_mensal","deaths_covid19":135633.0,"deaths_sars_2020":48745.0,"deaths_pneumonia_2020":1853671.0,"deaths_septicemia_2020":1505340.0,"deaths_total_2020":100855.0,"deaths_total_2019":95052.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-05-01","tipo":"mortalidade_mensal","deaths_covid19":770996.0,"deaths_sars_2020":186193.0,"deaths_pneumonia_2020":2397798.0,"deaths_septicemia_2020":1947896.0,"deaths_total_2020":133009.0,"deaths_total_2019":121655.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-06-01","tipo":"mortalidade_mensal","deaths_covid19":1594603.0,"deaths_sars_2020":270050.0,"deaths_pneumonia_2020":2744603.0,"deaths_septicemia_2020":2260780.0,"deaths_total_2020":165255.0,"deaths_total_2019":149968.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-07-01","tipo":"mortalidade_mensal","deaths_covid19":2515230.0,"deaths_sars_2020":332233.0,"deaths_pneumonia_2020":3253605.0,"deaths_septicemia_2020":2724403.0,"deaths_total_2020":198563.0,"deaths_total_2019":179005.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-08-01","tipo":"mortalidade_mensal","deaths_covid19":3401442.0,"deaths_sars_2020":377130.0,"deaths_pneumonia_2020":3677718.0,"deaths_septicemia_2020":3130029.0,"deaths_total_2020":231018.0,"deaths_total_2019":205814.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-09-01","tipo":"mortalidade_mensal","deaths_covid19":3967182.0,"deaths_sars_2020":399498.0,"deaths_pneumonia_2020":3977776.0,"deaths_septicemia_2020":3428684.0,"deaths_total_2020":259950.0,"deaths_total_2019":231154.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-10-01","tipo":"mortalidade_mensal","deaths_covid19":4619349.0,"deaths_sars_2020":440946.0,"deaths_pneumonia_2020":4565797.0,"deaths_septicemia_2020":3982430.0,"deaths_total_2020":289334.0,"deaths_total_2019":256110.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-11-01","tipo":"mortalidade_mensal","deaths_covid19":4860641.0,"deaths_sars_2020":449490.0,"deaths_pneumonia_2020":4834090.0,"deaths_septicemia_2020":4266933.0,"deaths_total_2020":315825.0,"deaths_total_2019":279392.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2020-12-01","tipo":"mortalidade_mensal","deaths_covid19":5608993.0,"deaths_sars_2020":492079.0,"deaths_pneumonia_2020":5399674.0,"deaths_septicemia_2020":4810979.0,"deaths_total_2020":338702.0,"deaths_total_2019":304156.0,"tecnologia":None,"demandante":None,"date_demanda":None,"analise_conitec":None,"decisao_ms":None,"portaria":None},
  {"date":"2021-06-25","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Oxigenação Extracorpórea (ECMO) para Suporte de Pacientes com Insuficiência Respiratória Grave e Refratária","demandante":"Ministro da Saúde em 29/04/2021","date_demanda":"2021-04-29","analise_conitec":"Desfavorável à incorporação","decisao_ms":"Não incorporação","portaria":"Portaria GM/MS nº 1.327 - Publicada em 25/06/2021"},
  {"date":"2021-09-09","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Rendesivir para tratamento de pacientes com Covid-19 hospitalizados","demandante":"Gilead Sciences em 22/04/2021","date_demanda":"2021-04-22","analise_conitec":"Desfavorável à incorporação","decisao_ms":"Não incorporação","portaria":"Portaria SCTIE/MS nº 60 - Publicada em 09/09/2021"},
  {"date":"2022-01-03","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Casirivimabe/imdevimabe para pacientes infectados por SARS-CoV-2","demandante":"Secretaria de Ciência, Tecnologia em 29/10/2021","date_demanda":"2021-10-29","analise_conitec":"Desfavorável à incorporação","decisao_ms":"Não incorporação","portaria":"Portaria SCTIE/MS nº 77 - Publicada em 03/01/2022"},
  {"date":"2022-01-26","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Diretrizes Brasileiras para Tratamento Medicamentoso Ambulatorial do Paciente com Covid-19","demandante":"Ministro da Saúde em 29/04/2021","date_demanda":"2021-04-29","analise_conitec":"Favorável à aprovação","decisao_ms":"Não aprovação","portaria":"Portaria SCTIE/MS nº 08/2022 - Publicada em 26/01/2022"},
  {"date":"2022-01-26","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Diretrizes Brasileiras para Tratamento Hospitalar - Capítulo 2: Tratamento Medicamentoso","demandante":"Ministro da Saúde em 29/04/2021","date_demanda":"2021-04-29","analise_conitec":"Favorável à aprovação","decisao_ms":"Aprovação com solicitação de atualização","portaria":"Portaria SCTIE/MS nº 05/2022 - Publicada em 26/01/2022"},
  {"date":"2022-01-26","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Diretrizes Brasileiras para Tratamento Hospitalar - Capítulo 3: Controle da Dor, Sedação e Delirium","demandante":"Ministro da Saúde em 29/04/2021","date_demanda":"2021-04-29","analise_conitec":"Favorável à aprovação","decisao_ms":"Aprovação","portaria":"Portaria SCTIE/MS nº 06/2022 - Publicada em 26/01/2022"},
  {"date":"2022-05-06","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Nirmatrelvir + ritonavir para tratamento da Covid-19 em adultos","demandante":"Secretaria Executiva em 05/04/2022","date_demanda":"2022-04-05","analise_conitec":"Favorável à incorporação","decisao_ms":"Incorporação","portaria":"Portaria SCTIE/MS nº 44 - Publicada em 06/05/2022"},
  {"date":"2022-09-12","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Tocilizumabe para tratamento de pacientes adultos com Covid-19 hospitalizados","demandante":"Ministro da Saúde em 14/04/2022","date_demanda":"2022-04-14","analise_conitec":"Favorável à incorporação","decisao_ms":"Incorporação","portaria":"Portaria SCTIE/MS nº 101 - Publicada em 12/09/2022"},
  {"date":"2022-12-29","tipo":"decisao_regulatoria_conitec","deaths_covid19":None,"deaths_sars_2020":None,"deaths_pneumonia_2020":None,"deaths_septicemia_2020":None,"deaths_total_2020":None,"deaths_total_2019":None,"tecnologia":"Vacina Pfizer/BioNTech para imunização de 6 meses a 5 anos para prevenção da Covid-19","demandante":"Secretaria de Vigilância em Saúde em 18/10/2022","date_demanda":"2022-10-18","analise_conitec":"Favorável à incorporação","decisao_ms":"Incorporação","portaria":"Portaria SCTIE/MS nº 181 - Publicada em 29/12/2022"}
]

# =============================================
# CRIAÇÃO DO DATAFRAME
# =============================================
df = pd.DataFrame(dados_json)
df['date']         = pd.to_datetime(df['date'])
df['date_demanda'] = pd.to_datetime(df['date_demanda'])

df_mortalidade = df[df['tipo'] == 'mortalidade_mensal'].copy()
df_tecnologias = df[df['tipo'] == 'decisao_regulatoria_conitec'].copy()

# =============================================
# DECISÕES DO MINISTÉRIO DA SAÚDE
# =============================================
print("--- Decisões do Ministério da Saúde ---")
display(df_tecnologias['decisao_ms'].value_counts(dropna=False).reset_index())

# =============================================
# TABELA DE VALORES MÍNIMO E MÁXIMO
# =============================================
lista_min_max = []

for col in df.columns:
    serie_limpa = df[col].dropna()
    tipo_dado   = str(df[col].dtype)

    if serie_limpa.empty:
        valor_min = 'N/A'
        valor_max = 'N/A'
    else:
        valor_min = serie_limpa.min()
        valor_max = serie_limpa.max()

    lista_min_max.append({
        'Coluna'      : col,
        'Tipo de Dado': tipo_dado,
        'Valor Mínimo': valor_min,
        'Valor Máximo': valor_max
    })

df_min_max = pd.DataFrame(lista_min_max)

print("\n--- Tabela de Valores Mínimo e Máximo ---")
display(df_min_max)

!pip install pyspark #instalação do pyspark

#====================carregamento dos dados direto============================================================
data = """date,tipo,deaths_covid19,deaths_sars_2020,deaths_pneumonia_2020,deaths_septicemia_2020,deaths_total_2020,deaths_total_2019,tecnologia,demandante,date_demanda,analise_conitec,decisao_ms,portaria
2020-01-01,mortalidade_mensal,52.0,1884.0,288523.0,235258.0,24654.0,24718.0,,,,,,
2020-02-01,mortalidade_mensal,264.0,4588.0,755567.0,634915.0,47461.0,46457.0,,,,,,
2020-03-01,mortalidade_mensal,4302.0,10134.0,1362963.0,1126913.0,73864.0,70868.0,,,,,,
2020-04-01,mortalidade_mensal,135633.0,48745.0,1853671.0,1505340.0,100855.0,95052.0,,,,,,
2020-05-01,mortalidade_mensal,770996.0,186193.0,2397798.0,1947896.0,133009.0,121655.0,,,,,,
2020-06-01,mortalidade_mensal,1594603.0,270050.0,2744603.0,2260780.0,165255.0,149968.0,,,,,,
2020-07-01,mortalidade_mensal,2515230.0,332233.0,3253605.0,2724403.0,198563.0,179005.0,,,,,,
2020-08-01,mortalidade_mensal,3401442.0,377130.0,3677718.0,3130029.0,231018.0,205814.0,,,,,,
2020-09-01,mortalidade_mensal,3967182.0,399498.0,3977776.0,3428684.0,259950.0,231154.0,,,,,,
2020-10-01,mortalidade_mensal,4619349.0,440946.0,4565797.0,3982430.0,289334.0,256110.0,,,,,,
2020-11-01,mortalidade_mensal,4860641.0,449490.0,4834090.0,4266933.0,315825.0,279392.0,,,,,,
2020-12-01,mortalidade_mensal,5608993.0,492079.0,5399674.0,4810979.0,338702.0,304156.0,,,,,,
2021-06-25,decisao_regulatoria_conitec,,,,,,,Oxigenação Extracorpórea (ECMO) para Suporte de Pacientes com Insuficiência Respiratória Grave e Refratária,Ministro da Saúde em 29/04/2021,2021-04-29,Desfavorável à incorporação,Não incorporação,Portaria GM/MS nº 1.327 - Publicada em 25/06/2021
2021-09-09,decisao_regulatoria_conitec,,,,,,,Rendesivir para tratamento de pacientes com Covid-19 hospitalizados com pneumonia e necessidade de suplementação de oxigênio,Gilead Sciences em 22/04/2021,2021-04-22,Desfavorável à incorporação,Não incorporação,Portaria SCTIE/MS nº 60 - Publicada em 09/09/2021
2022-01-03,decisao_regulatoria_conitec,,,,,,,Casirivimabe/imdevimabe para pacientes infectados por SARS-CoV-2 não hospitalizados de alto risco,"Secretaria de Ciência, Tecnologia, Inovação e Insumos Estratégicos em Saúde em 29/10/2021",2021-10-29,Desfavorável à incorporação,Não incorporação,Portaria SCTIE/MS nº 77 - Publicada em 03/01/2022
2022-01-26,decisao_regulatoria_conitec,,,,,,,Diretrizes Brasileiras para Tratamento Medicamentoso Ambulatorial do Paciente com Covid-19,Ministro da Saúde em 29/04/2021,2021-04-29,Favorável à aprovação,Não aprovação,Portaria SCTIE/MS nº 08/2022 - Publicada em 26/01/2022
2022-01-26,decisao_regulatoria_conitec,,,,,,,Diretrizes Brasileiras para Tratamento Hospitalar do Paciente com Covid-19 - Capítulo 2: Tratamento Medicamentoso,Ministro da Saúde em 29/04/2021,2021-04-29,Favorável à aprovação,Aprovação com solicitação de atualização,Portaria SCTIE/MS nº 05/2022 - Publicada em 26/01/2022
2022-01-26,decisao_regulatoria_conitec,,,,,,,"Diretrizes Brasileiras para Tratamento Hospitalar do Paciente com Covid-19 - Capítulo 3: Controle da Dor, Sedação e Delirium em Pacientes sob Ventilação Mecânica Invasiva",Ministro da Saúde em 29/04/2021,2021-04-29,Favorável à aprovação,Aprovação,Portaria SCTIE/MS nº 06/2022 - Publicada em 26/01/2022
2022-05-06,decisao_regulatoria_conitec,,,,,,,Nirmatrelvir + ritonavir para o tratamento da Covid-19 em adultos que não requerem oxigênio suplementar e que apresentam risco aumentado de progressão para Covid-19 grave,Secretaria Executiva em 05/04/2022,2022-04-05,Favorável à incorporação,Incorporação,Portaria SCTIE/MS nº 44 - Publicada em 06/05/2022
2022-09-12,decisao_regulatoria_conitec,,,,,,,Tocilizumabe para tratamento de pacientes adultos com Covid-19 hospitalizados,Ministro da Saúde em 14/04/2022,2022-04-14,Favorável à incorporação,Incorporação,Portaria SCTIE/MS nº 101 - Publicada em 12/09/2022
2022-12-29,decisao_regulatoria_conitec,,,,,,,Vacina Pfizer/BioNTech para a imunização ativa de indivíduos na faixa etária de 6 meses a 5 anos incompletos para a prevenção da Covid-19,Secretaria de Vigilância em Saúde em 18/10/2022,2022-10-18,Favorável à incorporação,Incorporação,Portaria SCTIE/MS nº 181 - Publicada em 29/12/2022"""

with open("obito_tecnologias_unificado.csv", "w", encoding="utf-8") as f:
    f.write(data)

print("Arquivo criado com sucesso!")

#==============Setup do pyspark======================:
from pyspark.sql import SparkSession
import matplotlib.pyplot as plt

spark = SparkSession.builder \
    .appName("Obitos_SQL") \
    .getOrCreate()

spark.sparkContext.setLogLevel("ERROR")
print("Spark pronto!")

# ============== Carregar e registrar tabela SQL ======================:
df = spark.read.csv(
    "obito_tecnologias_unificado.csv",
    header=True,
    inferSchema=True
)

df.createOrReplaceTempView("obitos")
print("Tabela registrada! Colunas:", df.columns)

spark.sql("SELECT * FROM obitos LIMIT 5").show(truncate=False)

spark.sql("""
    SELECT date, deaths_covid19, deaths_total_2020, deaths_total_2019
    FROM obitos WHERE tipo = 'mortalidade_mensal' ORDER BY date
""").show()

spark.sql("""
    SELECT date, deaths_covid19 FROM obitos
    WHERE tipo = 'mortalidade_mensal'
    ORDER BY deaths_covid19 DESC LIMIT 3
""").show()

spark.sql("""
    SELECT SUM(deaths_covid19) AS total_covid, SUM(deaths_sars_2020) AS total_sars,
           SUM(deaths_pneumonia_2020) AS total_pneumonia, SUM(deaths_septicemia_2020) AS total_septicemia
    FROM obitos WHERE tipo = 'mortalidade_mensal'
""").show()

spark.sql("""
    SELECT date, deaths_total_2020, deaths_total_2019,
           (deaths_total_2020 - deaths_total_2019) AS excesso_obitos
    FROM obitos WHERE tipo = 'mortalidade_mensal'
    ORDER BY excesso_obitos DESC
""").show()

spark.sql("""
    SELECT date, tecnologia, decisao_ms, analise_conitec, portaria
    FROM obitos WHERE tipo = 'decisao_regulatoria_conitec' ORDER BY date
""").show(truncate=False)

spark.sql("""
    SELECT decisao_ms, COUNT(*) AS quantidade FROM obitos
    WHERE tipo = 'decisao_regulatoria_conitec'
    GROUP BY decisao_ms ORDER BY quantidade DESC
""").show(truncate=False)

# ============== COLETA DE DADOS PARA OS GRÁFICOS ======================
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

pdf = spark.sql("""
    SELECT date, deaths_covid19, deaths_sars_2020, deaths_pneumonia_2020,
           deaths_septicemia_2020, deaths_total_2020, deaths_total_2019
    FROM obitos WHERE tipo = 'mortalidade_mensal' ORDER BY date
""").toPandas()

pdf_conitec = spark.sql("""
    SELECT date, tecnologia, decisao_ms FROM obitos
    WHERE tipo = 'decisao_regulatoria_conitec' ORDER BY date
""").toPandas()

meses = [d[5:7] + "/" + d[2:4] for d in pdf["date"].astype(str)]
fmt = mticker.FuncFormatter(lambda val, _: f"{int(val):,}".replace(",", "."))

# ============== GRÁFICO 1: Evolução mensal dos óbitos COVID-19 ======================
fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(meses, pdf["deaths_covid19"], marker="o", color="crimson", linewidth=2.5, markersize=7)
ax.fill_between(meses, pdf["deaths_covid19"], alpha=0.15, color="crimson")

for i, val in enumerate(pdf["deaths_covid19"]):
    ax.annotate(f"{int(val):,}".replace(",", "."),
                xy=(i, val), xytext=(0, 10),
                textcoords="offset points", ha="center", fontsize=8, color="crimson")

ax.set_title("Evolução Mensal dos Óbitos por COVID-19 (2020)", fontsize=14, fontweight="bold")
ax.set_xlabel("Mês")
ax.set_ylabel("Óbitos")
ax.yaxis.set_major_formatter(fmt)
ax.set_xticks(range(len(meses)))
ax.set_xticklabels(meses, rotation=45, ha="right")
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

# ============== GRÁFICO 2: Comparação de causas de óbito por mês ======================:
x = np.arange(len(meses))
largura = 0.22

fig, ax = plt.subplots(figsize=(16, 6))
ax.bar(x - largura*1.5, pdf["deaths_covid19"],       largura, label="COVID-19",    color="crimson")
ax.bar(x - largura*0.5, pdf["deaths_sars_2020"],     largura, label="SARS",        color="steelblue")
ax.bar(x + largura*0.5, pdf["deaths_pneumonia_2020"] / 10, largura, label="Pneumonia (/10)", color="mediumseagreen")
ax.bar(x + largura*1.5, pdf["deaths_septicemia_2020"] / 10, largura, label="Septicemia (/10)", color="darkorange")

ax.set_title("Comparação de Causas de Óbito por Mês (2020)\n* Pneumonia e Septicemia divididas por 10 para escala", fontsize=13, fontweight="bold")
ax.set_xlabel("Mês")
ax.set_ylabel("Óbitos")
ax.yaxis.set_major_formatter(fmt)
ax.set_xticks(x)
ax.set_xticklabels(meses, rotation=45, ha="right")
ax.legend()
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

# ============== GRÁFICO 3: Excesso de óbitos 2020 vs 2019 ======================:
excesso = pdf["deaths_total_2020"] - pdf["deaths_total_2019"]
cores = ["crimson" if v > 0 else "steelblue" for v in excesso]

fig, ax = plt.subplots(figsize=(14, 5))
barras = ax.bar(meses, excesso, color=cores, edgecolor="white", linewidth=0.7)

for bar, val in zip(barras, excesso):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 100,
            f"{int(val):,}".replace(",", "."),
            ha="center", va="bottom", fontsize=8, fontweight="bold")

ax.axhline(0, color="black", linewidth=1)
ax.set_title("Excesso de Óbitos: 2020 vs 2019 (Total Mensal)", fontsize=14, fontweight="bold")
ax.set_xlabel("Mês")
ax.set_ylabel("Diferença de Óbitos")
ax.yaxis.set_major_formatter(fmt)
ax.set_xticklabels(meses, rotation=45, ha="right")
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

# ============== GRÁFICO 4: Totais acumulados por causa ======================:
totais = {
    "COVID-19":    pdf["deaths_covid19"].sum(),
    "SARS":        pdf["deaths_sars_2020"].sum(),
    "Pneumonia":   pdf["deaths_pneumonia_2020"].sum(),
    "Septicemia":  pdf["deaths_septicemia_2020"].sum(),
}
cores_pizza = ["crimson", "steelblue", "mediumseagreen", "darkorange"]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Pizza
wedges, texts, autotexts = ax1.pie(
    totais.values(), labels=totais.keys(), colors=cores_pizza,
    autopct="%1.1f%%", startangle=140,
    wedgeprops=dict(edgecolor="white", linewidth=2)
)
for t in autotexts:
    t.set_fontsize(10)
    t.set_fontweight("bold")
ax1.set_title("Proporção Total por Causa (2020)", fontsize=13, fontweight="bold")

# Barras horizontais
nomes = list(totais.keys())
valores = list(totais.values())
barras_h = ax2.barh(nomes, valores, color=cores_pizza, edgecolor="white")
for bar, val in zip(barras_h, valores):
    ax2.text(val + max(valores)*0.01, bar.get_y() + bar.get_height()/2,
             f"{int(val):,}".replace(",", "."),
             va="center", fontsize=10, fontweight="bold")
ax2.set_title("Total Acumulado por Causa (2020)", fontsize=13, fontweight="bold")
ax2.set_xlabel("Total de Óbitos")
ax2.xaxis.set_major_formatter(fmt)
ax2.grid(axis="x", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

# ============== GRÁFICO 5: Decisões do CONITEC ======================:
contagem = pdf_conitec["decisao_ms"].value_counts()

fig, ax = plt.subplots(figsize=(10, 5))
barras_c = ax.bar(contagem.index, contagem.values, color=["tomato", "mediumseagreen", "steelblue", "gold"], edgecolor="white")

for bar, val in zip(barras_c, contagem.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
            str(val), ha="center", fontsize=12, fontweight="bold")

ax.set_title("Decisões do Ministério da Saúde — CONITEC (COVID-19)", fontsize=13, fontweight="bold")
ax.set_xlabel("Decisão")
ax.set_ylabel("Quantidade")
ax.set_xticklabels(contagem.index, rotation=20, ha="right")
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

# =============================================
#Histograma
# =============================================
pdf_hist = spark.sql("""
    SELECT date, deaths_covid19,
           (deaths_total_2020 - deaths_total_2019) AS excesso_obitos
    FROM obitos
    WHERE tipo = 'mortalidade_mensal'
    ORDER BY date
""").toPandas()

meses = [d[5:7] + "/" + d[2:4] for d in pdf_hist["date"].astype(str)]

x = range(len(meses))
largura = 0.35

fig, ax = plt.subplots(figsize=(14, 6))

barras1 = ax.bar([i - largura/2 for i in x], pdf_hist["deaths_covid19"],
                 width=largura, color="crimson", label="Óbitos COVID-19")
barras2 = ax.bar([i + largura/2 for i in x], pdf_hist["excesso_obitos"],
                 width=largura, color="orange", label="Excesso de óbitos (2020 vs 2019)")

ax.set_xticks(list(x))
ax.set_xticklabels(meses, rotation=45, ha="right")
ax.set_title("Histograma: Óbitos COVID-19 e Excesso de Mortalidade por Mês (2020)", fontsize=14)
ax.set_xlabel("Mês")
ax.set_ylabel("Número de Óbitos")
ax.legend()
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda val, _: f"{int(val):,}".replace(",", ".")))

plt.tight_layout()
plt.show()

# ============== REMOÇÃO DE OUTLIERS ======================

# Calcula limites IQR e cria tabela limpa
quartis = spark.sql("""
    SELECT
        percentile_approx(CAST(deaths_covid19 AS DOUBLE), 0.25) AS q1,
        percentile_approx(CAST(deaths_covid19 AS DOUBLE), 0.75) AS q3,
        percentile_approx(CAST(deaths_covid19 AS DOUBLE), 0.75) -
        percentile_approx(CAST(deaths_covid19 AS DOUBLE), 0.25) AS iqr
    FROM obitos
    WHERE tipo = 'mortalidade_mensal'
      AND deaths_covid19 IS NOT NULL
""").collect()[0]

lim_inf = quartis["q1"] - 1.5 * quartis["iqr"]
lim_sup = quartis["q3"] + 1.5 * quartis["iqr"]

print(f"Limite inferior: {lim_inf:,.0f} | Limite superior: {lim_sup:,.0f}")

spark.sql(f"""
    SELECT * FROM obitos
    WHERE tipo != 'mortalidade_mensal'
       OR (deaths_covid19 IS NOT NULL
           AND CAST(deaths_covid19 AS DOUBLE) BETWEEN {lim_inf} AND {lim_sup})
""").createOrReplaceTempView("obitos_sem_outliers")

# Confere o que foi removido
spark.sql("""
    SELECT 'com_outliers' AS versao, COUNT(*) AS linhas, ROUND(AVG(CAST(deaths_covid19 AS DOUBLE)), 0) AS media
    FROM obitos WHERE tipo = 'mortalidade_mensal'
    UNION ALL
    SELECT 'sem_outliers' AS versao, COUNT(*) AS linhas, ROUND(AVG(CAST(deaths_covid19 AS DOUBLE)), 0) AS media
    FROM obitos_sem_outliers WHERE tipo = 'mortalidade_mensal'
""").show()

# ============== GRÁFICO : Densidade por causa de óbito ======================
from scipy.stats import gaussian_kde

# garante que as colunas são numéricas (resolve o inferSchema=True)
colunas_dens = {
    "deaths_covid19":         ("COVID-19",  "crimson"),
    "deaths_sars_2020":       ("SARS",       "steelblue"),
    "deaths_pneumonia_2020":  ("Pneumonia",  "mediumseagreen"),
    "deaths_septicemia_2020": ("Septicemia", "darkorange"),
}

fig, axes = plt.subplots(2, 2, figsize=(15, 10))
axes = axes.flatten()

for ax, (col, (label, cor)) in zip(axes, colunas_dens.items()):
    valores = pdf[col].astype(float).dropna().values

    # curva KDE
    kde = gaussian_kde(valores, bw_method=0.4)
    x   = np.linspace(valores.min(), valores.max(), 300)
    y   = kde(x)

    ax.plot(x, y, color=cor, linewidth=2.5)
    ax.fill_between(x, y, alpha=0.2, color=cor)

    # linhas de média e mediana
    media   = valores.mean()
    mediana = np.median(valores)
    ax.axvline(media,   color="black", linestyle="--", linewidth=1.5,
               label=f"Média:   {int(media):,}".replace(",", "."))
    ax.axvline(mediana, color="gray",  linestyle=":",  linewidth=1.5,
               label=f"Mediana: {int(mediana):,}".replace(",", "."))

    ax.set_title(f"Densidade — {label}", fontsize=13, fontweight="bold")
    ax.set_xlabel("Óbitos")
    ax.set_ylabel("Densidade")
    ax.xaxis.set_major_formatter(fmt)
    ax.legend(fontsize=9)
    ax.grid(linestyle="--", alpha=0.4)

plt.suptitle("Distribuição de Densidade por Causa de Óbito (2020)",
             fontsize=15, fontweight="bold", y=1.01)
plt.tight_layout()
plt.show()

# ============================================================
#  Análise COVID-19 — Óbitos e Decisões CONITEC
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# ── DADOS HARDCODED ──────────────────────────────────────────

meses = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']

# Valores acumulados mensais (2020)
total_2020_acum = [24654, 47461, 73864, 100855, 133009, 165255,
                   198563, 231018, 259950, 289334, 315825, 338702]

# Valores acumulados mensais (2019)
total_2019_acum = [24718, 46457, 70868, 95052, 121655, 149968,
                   179005, 205814, 231154, 256110, 279392, 304156]

# Registros COVID-19 acumulados
covid_acum      = [52, 264, 4302, 135633, 770996, 1594603,
                   2515230, 3401442, 3967182, 4619349, 4860641, 5608993]

# Decisões CONITEC
tecnologias = [
    'ECMO',
    'Remdesivir',
    'Casirivimabe/imdevimabe',
    'Diretrizes Amb. COVID-19',
    'Diretrizes Hosp. Cap.2',
    'Diretrizes Hosp. Cap.3',
    'Nirmatrelvir + ritonavir',
    'Tocilizumabe',
    'Vacina Pfizer (6m–5a)',
]

analise_conitec = [
    'Desfavorável',
    'Desfavorável',
    'Desfavorável',
    'Favorável à aprovação',
    'Favorável à aprovação',
    'Favorável à aprovação',
    'Favorável à incorporação',
    'Favorável à incorporação',
    'Favorável à incorporação',
]

decisao_ms = [
    'Não incorporação',
    'Não incorporação',
    'Não incorporação',
    'Não aprovação',
    'Aprovação condicional',
    'Aprovação',
    'Incorporação',
    'Incorporação',
    'Incorporação',
]

# ── PRÉ-PROCESSAMENTO ────────────────────────────────────────

def to_mensal(acum):
    a = np.array(acum, dtype=float)
    return np.concatenate([[a[0]], np.diff(a)])

mensal_2020 = to_mensal(total_2020_acum)
mensal_2019 = to_mensal(total_2019_acum)
diferenca   = mensal_2020 - mensal_2019

# Contagens CONITEC
from collections import Counter
cont_analise = Counter(analise_conitec)
cont_decisao = Counter(decisao_ms)

# ── ESTILO GERAL ─────────────────────────────────────────────

plt.rcParams.update({
    'font.family'  : 'DejaVu Sans',
    'axes.spines.top'   : False,
    'axes.spines.right' : False,
    'axes.grid'         : True,
    'grid.linestyle'    : '--',
    'grid.alpha'        : 0.35,
    'figure.dpi'        : 130,
})

VERMELHO = '#c0392b'
CINZA    = '#7f8c8d'
AZUL     = '#2471a3'
VERDE    = '#1d9e75'
LARANJA  = '#e67e22'

# ── FIGURA PRINCIPAL (2x2) ───────────────────────────────────

fig, axes = plt.subplots(2, 2, figsize=(16, 11))
fig.suptitle('COVID-19 no Brasil (2020) — Mortalidade e Regulação de Tecnologias',
             fontsize=15, fontweight='bold', y=1.01)

# ────────────────────────────────────────────────────────────
#  GRÁFICO 1 — Barras agrupadas: óbitos mensais 2019 vs 2020
# ────────────────────────────────────────────────────────────
ax1 = axes[0, 0]
x = np.arange(len(meses))
w = 0.38

ax1.bar(x - w/2, mensal_2019, w, label='2019', color=CINZA,    alpha=0.85)
ax1.bar(x + w/2, mensal_2020, w, label='2020', color=VERMELHO, alpha=0.85)

for i, (v19, v20) in enumerate(zip(mensal_2019, mensal_2020)):
    pct = (v20 - v19) / v19 * 100
    cor = VERMELHO if pct > 0 else VERDE
    ax1.text(i, max(v19, v20) + 250, f'{pct:+.0f}%',
             ha='center', fontsize=7.5, color=cor, fontweight='bold')

ax1.set_title('Óbitos mensais — todas as causas', fontweight='bold')
ax1.set_xticks(x); ax1.set_xticklabels(meses, fontsize=8)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{int(v):,}'))
ax1.set_ylabel('Óbitos / mês')
ax1.legend(framealpha=0.4)

# ────────────────────────────────────────────────────────────
#  GRÁFICO 2 — Colunas: excesso de mortalidade por mês
# ────────────────────────────────────────────────────────────
ax2 = axes[0, 1]

cores_exc = [VERMELHO if d > 0 else VERDE for d in diferenca]
barras = ax2.bar(meses, diferenca, color=cores_exc, alpha=0.85, edgecolor='white')

for barra, val in zip(barras, diferenca):
    ax2.text(barra.get_x() + barra.get_width()/2,
             barra.get_height() + 50,
             f'{int(val):+,}', ha='center', fontsize=7.5,
             color=VERMELHO if val > 0 else VERDE, fontweight='bold')

ax2.axhline(0, color='black', linewidth=0.8)
ax2.set_title('Excesso de mortalidade (2020 − 2019)', fontweight='bold')
ax2.set_ylabel('Óbitos extras / mês')
ax2.tick_params(axis='x', labelsize=8)
ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{int(v):,}'))

# ────────────────────────────────────────────────────────────
#  GRÁFICO 3 — Colunas: registros COVID-19 acumulados
# ────────────────────────────────────────────────────────────
ax3 = axes[1, 0]

degradê = plt.cm.Blues(np.linspace(0.3, 0.9, 12))
barras3 = ax3.bar(meses, covid_acum, color=degradê, edgecolor='#1a5276', linewidth=0.5)

for b, v in zip(barras3, covid_acum):
    label = f'{v/1e6:.2f}M' if v >= 1e6 else f'{int(v):,}'
    ax3.text(b.get_x() + b.get_width()/2, b.get_height() + 60000,
             label, ha='center', fontsize=7, color='#1a5276', fontweight='bold')

ax3.set_title('Registros COVID-19 acumulados (2020)', fontweight='bold')
ax3.set_ylabel('Registros acumulados')
ax3.tick_params(axis='x', labelsize=8)
ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{v/1e6:.1f}M'))

# ────────────────────────────────────────────────────────────
#  GRÁFICO 4 — Barras horizontais: decisões CONITEC
# ────────────────────────────────────────────────────────────
ax4 = axes[1, 1]

labels_d = list(cont_decisao.keys())
valores_d = list(cont_decisao.values())

def cor_decisao(label):
    l = label.lower()
    if 'incorporação' == l:    return VERDE
    if 'não' in l:             return VERMELHO
    if 'condicional' in l:     return LARANJA
    if 'aprovação' == l:       return '#2ecc71'
    return CINZA

cores_d = [cor_decisao(l) for l in labels_d]

barras4 = ax4.barh(labels_d, valores_d, color=cores_d, alpha=0.85, edgecolor='white', height=0.55)

for b, v in zip(barras4, valores_d):
    ax4.text(v + 0.05, b.get_y() + b.get_height()/2,
             str(v), va='center', fontweight='bold', fontsize=10)

ax4.set_title('Decisão do Ministério da Saúde (CONITEC)', fontweight='bold')
ax4.set_xlabel('Nº de tecnologias')
ax4.set_xlim(0, max(valores_d) + 1)
ax4.tick_params(axis='y', labelsize=9)
ax4.grid(axis='x')

# ── LEGENDA DE CORES (gráfico 4) ──────────────────────────────
from matplotlib.patches import Patch
legenda = [
    Patch(color=VERDE,    label='Incorporação'),
    Patch(color='#2ecc71',label='Aprovação'),
    Patch(color=LARANJA,  label='Aprovação condicional'),
    Patch(color=VERMELHO, label='Não incorporação / Não aprovação'),
]
ax4.legend(handles=legenda, fontsize=8, loc='lower right', framealpha=0.4)

# ── RODAPÉ ───────────────────────────────────────────────────
fig.text(0.5, -0.01,
         'Fonte: obito_tecnologias_unificado.csv  |  Dados acumulados convertidos em incrementos mensais',
         ha='center', fontsize=9, color='gray')

plt.tight_layout()
plt.savefig('analise_covid_conitec.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ Gráfico salvo como 'analise_covid_conitec.png'")
print(f"\n📊 Excesso total de mortalidade em 2020: {int(sum(diferenca)):,} óbitos")
print(f"📊 Variação percentual anual           : {(sum(mensal_2020)/sum(mensal_2019)-1)*100:+.1f}%")
print(f"📊 Registros COVID-19 acumulados (dez) : {int(covid_acum[-1]):,}")
print(f"📋 Tecnologias incorporadas ao SUS     : {cont_decisao.get('Incorporação', 0)}")
print(f"📋 Tecnologias rejeitadas              : {cont_decisao.get('Não incorporação', 0) + cont_decisao.get('Não aprovação', 0)}")

# ============================================================
#  Evolução COVID-19 no Brasil (2020) + Linha do Tempo CONITEC
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import matplotlib.dates as mdates
from matplotlib.patches import Patch
from datetime import datetime

# ── DADOS BRUTOS (extraídos do CSV obito_tecnologias_unificado) ──
# Todos os valores estão no formato ACUMULADO mensal (jan–dez 2020)

meses_label = ['Jan','Fev','Mar','Abr','Mai','Jun',
                'Jul','Ago','Set','Out','Nov','Dez']

# Datas como objetos datetime para o eixo temporal
datas_2020 = [datetime(2020, m, 1) for m in range(1, 13)]

# Óbitos totais (todas as causas) acumulados
total_2020_acum = [24654,  47461,  73864,  100855, 133009, 165255,
                   198563, 231018, 259950, 289334, 315825, 338702]

total_2019_acum = [24718,  46457,  70868,  95052,  121655, 149968,
                   179005, 205814, 231154, 256110, 279392, 304156]

# Registros acumulados por causa (sistema de notificação SIVAM)
covid_acum    = [52,      264,     4302,    135633,  770996,  1594603,
                 2515230, 3401442, 3967182, 4619349, 4860641, 5608993]

sars_acum     = [1884,   4588,   10134,   48745,   186193,  270050,
                 332233, 377130, 399498,  440946,  449490,  492079]

pneum_acum    = [288523,  755567,  1362963, 1853671, 2397798, 2744603,
                 3253605, 3677718, 3977776, 4565797, 4834090, 5399674]

septic_acum   = [235258,  634915,  1126913, 1505340, 1947896, 2260780,
                 2724403, 3130029, 3428684, 3982430, 4266933, 4810979]

# ── FUNÇÃO: converte acumulado em incremento mensal ──────────
def mensal(acum):
    a = np.array(acum, dtype=float)
    return np.concatenate([[a[0]], np.diff(a)])

# Incrementos mensais de cada série
inc_total_2020 = mensal(total_2020_acum)
inc_total_2019 = mensal(total_2019_acum)
inc_covid      = mensal(covid_acum)
inc_sars       = mensal(sars_acum)
inc_pneum      = mensal(pneum_acum)
inc_septic     = mensal(septic_acum)

# Excesso de mortalidade = diferença entre 2020 e 2019
excesso = inc_total_2020 - inc_total_2019

# ── DADOS CONITEC: tecnologias avaliadas entre 2021 e 2022 ───
conitec_datas = [
    datetime(2021,  6, 25),   # ECMO
    datetime(2021,  9,  9),   # Remdesivir
    datetime(2022,  1,  3),   # Casirivimabe
    datetime(2022,  1, 26),   # Dir. Ambulatorial
    datetime(2022,  1, 26),   # Dir. Hosp. Cap.2
    datetime(2022,  1, 26),   # Dir. Hosp. Cap.3
    datetime(2022,  5,  6),   # Nirmatrelvir + ritonavir
    datetime(2022,  9, 12),   # Tocilizumabe
    datetime(2022, 12, 29),   # Vacina Pfizer (6m–5a)
]

conitec_labels = [
    'ECMO', 'Remdesivir', 'Casirivimabe',
    'Dir. Ambulatorial', 'Dir. Hosp. Cap.2', 'Dir. Hosp. Cap.3',
    'Nirmatrelvir', 'Tocilizumabe', 'Vacina Pfizer (6m–5a)',
]

conitec_decisao = [
    'Não incorporação', 'Não incorporação', 'Não incorporação',
    'Não aprovação', 'Aprovação condicional', 'Aprovação',
    'Incorporação', 'Incorporação', 'Incorporação',
]

# ── PALETA DE CORES ──────────────────────────────────────────
VERMELHO = '#c0392b'
CINZA    = '#95a5a6'
AZUL     = '#2471a3'
VERDE    = '#1d9e75'
LARANJA  = '#e67e22'
ROXO     = '#8e44ad'
AMARELO  = '#d4ac0d'

def cor_decisao(d):
    """Retorna cor conforme o resultado da decisão regulatória."""
    if d in ('Incorporação', 'Aprovação'):  return VERDE
    if 'condicional' in d:                  return LARANJA
    return VERMELHO

# ── ESTILO GLOBAL ─────────────────────────────────────────────
plt.rcParams.update({
    'font.family'       : 'DejaVu Sans',
    'axes.spines.top'   : False,
    'axes.spines.right' : False,
    'grid.linestyle'    : '--',
    'grid.alpha'        : 0.3,
    'figure.dpi'        : 130,
})

# ── LAYOUT COM GRIDSPEC (3 linhas, 2 colunas) ─────────────────
fig = plt.figure(figsize=(20, 16))
gs  = gridspec.GridSpec(3, 2, figure=fig,
                         hspace=0.52, wspace=0.32,
                         height_ratios=[1.1, 1, 1])

# Gráfico 1 ocupa a linha inteira no topo
ax1 = fig.add_subplot(gs[0, :])
# Os demais ocupam metade cada
ax2 = fig.add_subplot(gs[1, 0])
ax3 = fig.add_subplot(gs[1, 1])
ax4 = fig.add_subplot(gs[2, 0])
ax5 = fig.add_subplot(gs[2, 1])

fig.suptitle('Evolução da COVID-19 no Brasil — Mortalidade, Notificações e Regulação',
             fontsize=16, fontweight='bold', y=1.01)

# ════════════════════════════════════════════════════════════
#  GRÁFICO 1 (topo, largura total)
#  Evolução mensal de óbitos totais 2019 vs 2020
#  Eixo secundário mostra a curva de notificações COVID-19
#  O preenchimento entre as curvas destaca o excesso de mortalidade
# ════════════════════════════════════════════════════════════
ax1.plot(datas_2020, inc_total_2019, color=CINZA,    linewidth=2.2,
         linestyle='--', label='Óbitos 2019 (baseline)', zorder=3)
ax1.plot(datas_2020, inc_total_2020, color=VERMELHO, linewidth=2.5,
         marker='o', markersize=6, label='Óbitos 2020', zorder=4)

# Área sombreada entre as duas curvas = excesso de mortalidade
ax1.fill_between(datas_2020, inc_total_2019, inc_total_2020,
                 where=(inc_total_2020 >= inc_total_2019),
                 alpha=0.18, color=VERMELHO, label='Excesso de mortalidade')

# Eixo secundário para os registros COVID-19 (escala muito maior)
ax1b = ax1.twinx()
ax1b.bar(datas_2020, inc_covid, width=20,
         color=AZUL, alpha=0.25, label='Registros COVID-19 (mensal)')
ax1b.plot(datas_2020, inc_covid, color=AZUL, linewidth=1.8,
          linestyle=':', marker='s', markersize=4)
ax1b.set_ylabel('Registros COVID-19 / mês', color=AZUL, fontsize=9)
ax1b.tick_params(axis='y', labelcolor=AZUL, labelsize=8)
ax1b.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{v/1e6:.1f}M'))
ax1b.spines['top'].set_visible(False)

# Formata o eixo X como meses
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
ax1.xaxis.set_major_locator(mdates.MonthLocator())
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{int(v):,}'))
ax1.set_ylabel('Óbitos / mês (todas as causas)', fontsize=9)
ax1.set_title('Evolução mensal de óbitos (2019 vs 2020) e registros COVID-19',
              fontweight='bold', fontsize=12)
ax1.grid(True)

# Legenda combinada dos dois eixos
handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax1b.get_legend_handles_labels()
ax1.legend(handles1 + handles2, labels1 + labels2,
           loc='upper left', fontsize=8.5, framealpha=0.5)

# ════════════════════════════════════════════════════════════
#  GRÁFICO 2 (linha 2, esquerda)
#  Curvas acumuladas de mortalidade total 2019 vs 2020
#  A área entre as curvas representa o acúmulo do excesso
# ════════════════════════════════════════════════════════════
ax2.plot(datas_2020, total_2019_acum, color=CINZA, linewidth=2,
         linestyle='--', label='Acumulado 2019')
ax2.plot(datas_2020, total_2020_acum, color=VERMELHO, linewidth=2.5,
         marker='o', markersize=5, label='Acumulado 2020')

# Preenchimento acumulado do excesso
ax2.fill_between(datas_2020, total_2019_acum, total_2020_acum,
                 alpha=0.2, color=VERMELHO)

ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
ax2.xaxis.set_major_locator(mdates.MonthLocator())
ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{int(v):,}'))
ax2.set_title('Mortalidade acumulada: 2019 vs 2020', fontweight='bold')
ax2.set_ylabel('Óbitos acumulados')
ax2.legend(fontsize=8.5, framealpha=0.5)
ax2.grid(True)

# Anota o total acumulado final de cada série
ax2.annotate(f'{total_2019_acum[-1]:,}',
             xy=(datas_2020[-1], total_2019_acum[-1]),
             xytext=(-38, -14), textcoords='offset points',
             fontsize=8, color=CINZA, fontweight='bold')
ax2.annotate(f'{total_2020_acum[-1]:,}',
             xy=(datas_2020[-1], total_2020_acum[-1]),
             xytext=(-38, 6), textcoords='offset points',
             fontsize=8, color=VERMELHO, fontweight='bold')

# ════════════════════════════════════════════════════════════
#  GRÁFICO 3 (linha 2, direita)
#  Evolução acumulada do SARS e COVID-19 juntos
#  Permite ver o crescimento do COVID no contexto do SARS geral
# ════════════════════════════════════════════════════════════
ax3.fill_between(datas_2020, 0, sars_acum,
                 color=LARANJA, alpha=0.35, label='SARS (acumulado)')
ax3.fill_between(datas_2020, 0, covid_acum,
                 color=AZUL,   alpha=0.35, label='COVID-19 (acumulado)')

ax3.plot(datas_2020, sars_acum,  color=LARANJA, linewidth=2,   marker='o', markersize=4)
ax3.plot(datas_2020, covid_acum, color=AZUL,    linewidth=2.2, marker='s', markersize=4)

ax3.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
ax3.xaxis.set_major_locator(mdates.MonthLocator())
ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{v/1e6:.1f}M'))
ax3.set_title('Evolução acumulada: SARS vs COVID-19 (2020)', fontweight='bold')
ax3.set_ylabel('Registros acumulados')
ax3.legend(fontsize=8.5, framealpha=0.5)
ax3.grid(True)

# ════════════════════════════════════════════════════════════
#  GRÁFICO 4 (linha 3, esquerda)
#  Evolução mensal de pneumonia e septicemia (escala normalizada)
#  Mostra se a pandemia deslocou a pressão para outras causas
# ════════════════════════════════════════════════════════════
ax4.plot(datas_2020, inc_pneum,  color=ROXO,    linewidth=2.2,
         marker='o', markersize=5, label='Pneumonia')
ax4.plot(datas_2020, inc_septic, color=AMARELO, linewidth=2.2,
         marker='s', markersize=5, label='Septicemia')
ax4.fill_between(datas_2020, inc_pneum,  alpha=0.12, color=ROXO)
ax4.fill_between(datas_2020, inc_septic, alpha=0.12, color=AMARELO)

ax4.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
ax4.xaxis.set_major_locator(mdates.MonthLocator())
ax4.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v,_: f'{v/1e3:.0f}k'))
ax4.set_title('Evolução mensal: Pneumonia e Septicemia (2020)', fontweight='bold')
ax4.set_ylabel('Registros mensais')
ax4.legend(fontsize=8.5, framealpha=0.5)
ax4.grid(True)

# ════════════════════════════════════════════════════════════
#  GRÁFICO 5 (linha 3, direita)
#  Linha do tempo das decisões CONITEC (2021–2022)
#  Cada ponto representa uma tecnologia avaliada
#  Cor = resultado da decisão do Ministério da Saúde
# ════════════════════════════════════════════════════════════
ax5.set_xlim(datetime(2021, 4, 1), datetime(2023, 2, 1))
ax5.set_ylim(-0.5, len(conitec_labels) - 0.5)
ax5.grid(axis='x', linestyle='--', alpha=0.3)
ax5.spines['left'].set_visible(False)
ax5.spines['bottom'].set_position(('data', -0.5))

# Linha horizontal de base da timeline
ax5.axhline(-0.5, color='black', linewidth=0.5)

# Plota cada decisão como um ponto colorido + rótulo
for i, (data, label, dec) in enumerate(
        zip(conitec_datas, conitec_labels, conitec_decisao)):
    cor = cor_decisao(dec)
    ax5.scatter(data, i, color=cor, s=130, zorder=5, edgecolors='white', linewidth=1.2)
    # Linha conectando o ponto até o nome
    ax5.plot([data, data], [i - 0.35, i], color=cor, linewidth=0.8, alpha=0.5)
    # Rótulo à direita do ponto
    ax5.text(data, i + 0.32, label, ha='center', va='bottom',
             fontsize=7.5, fontweight='bold', color=cor)
    # Decisão abaixo do ponto
    ax5.text(data, i - 0.42, dec, ha='center', va='top',
             fontsize=6.5, color='gray', style='italic')

ax5.xaxis.set_major_formatter(mdates.DateFormatter('%b\n%Y'))
ax5.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
ax5.set_yticks([])
ax5.set_title('Linha do tempo — Decisões CONITEC (2021–2022)', fontweight='bold')

# Legenda de cores
legenda5 = [
    Patch(color=VERDE,   label='Incorporação / Aprovação'),
    Patch(color=LARANJA, label='Aprovação condicional'),
    Patch(color=VERMELHO,label='Não incorporação / Não aprovação'),
]
ax5.legend(handles=legenda5, fontsize=7.5, loc='lower right', framealpha=0.45)

# ── RODAPÉ ───────────────────────────────────────────────────
fig.text(0.5, -0.01,
         'Fonte: obito_tecnologias_unificado.csv  |  '
         'Dados acumulados convertidos em incrementos mensais  |  '
         'Notificações via SIVAM/SIM',
         ha='center', fontsize=8.5, color='gray')

plt.savefig('evolucao_covid_conitec.png', dpi=150, bbox_inches='tight')
plt.show()

# ── RESUMO NO TERMINAL ────────────────────────────────────────
print('\n✅ Gráfico salvo como evolucao_covid_conitec.png')
print(f'\n📈 Pico de excesso de mortalidade : {meses_label[np.argmax(excesso)]} '
      f'(+{int(np.max(excesso)):,} óbitos vs 2019)')
print(f'📈 Excesso total acumulado (2020)  : +{int(np.sum(excesso)):,} óbitos')
print(f'📈 Maior mês de registros COVID-19 : {meses_label[np.argmax(inc_covid)]} '
      f'({int(np.max(inc_covid)):,} registros)')
print(f'📋 Tecnologias incorporadas ao SUS : '
      f'{sum(1 for d in conitec_decisao if d == "Incorporação")}')
print(f'📋 Primeira incorporação           : '
      f'{conitec_labels[conitec_decisao.index("Incorporação")]} '
      f'({conitec_datas[conitec_decisao.index("Incorporação")].strftime("%d/%m/%Y")})')

# ============================================================
#  Nuvem de Palavras — obito_tecnologias_unificado.csv
#  Texto extraído diretamente das colunas textuais do arquivo
# ============================================================

!pip install wordcloud -q

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from wordcloud import WordCloud
from collections import Counter
from matplotlib.patches import Patch
import re

# ── TEXTO EXTRAÍDO DAS COLUNAS TEXTUAIS DO CSV ───────────────
# Cada lista abaixo corresponde aos valores reais de uma coluna

# Coluna 'tipo' — 12 linhas de mortalidade, 9 de decisão CONITEC
col_tipo = (
    ["mortalidade mensal"] * 12 +
    ["decisao regulatoria conitec"] * 9
)

# Coluna 'tecnologia' — descrição completa de cada tecnologia avaliada
col_tecnologia = [
    "Oxigenação Extracorpórea ECMO Suporte Pacientes Insuficiência Respiratória Grave Refratária",
    "Remdesivir tratamento pacientes Covid-19 hospitalizados pneumonia necessidade suplementação oxigênio",
    "Casirivimabe imdevimabe pacientes infectados SARS-CoV-2 não hospitalizados alto risco",
    "Diretrizes Brasileiras Tratamento Medicamentoso Ambulatorial Paciente Covid-19",
    "Diretrizes Brasileiras Tratamento Hospitalar Paciente Covid-19 Capítulo Tratamento Medicamentoso",
    "Diretrizes Brasileiras Tratamento Hospitalar Paciente Covid-19 Capítulo Controle Dor Sedação Delirium Pacientes Ventilação Mecânica Invasiva",
    "Nirmatrelvir ritonavir tratamento Covid-19 adultos oxigênio suplementar risco aumentado progressão Covid-19 grave",
    "Tocilizumabe tratamento pacientes adultos Covid-19 hospitalizados",
    "Vacina Pfizer BioNTech imunização ativa indivíduos faixa etária meses anos prevenção Covid-19",
]

# Coluna 'demandante' — quem solicitou a avaliação
col_demandante = [
    "Ministro Saúde",
    "Gilead Sciences",
    "Secretaria Ciência Tecnologia Inovação Insumos Estratégicos Saúde",
    "Ministro Saúde",
    "Ministro Saúde",
    "Ministro Saúde",
    "Secretaria Executiva",
    "Ministro Saúde",
    "Secretaria Vigilância Saúde",
]

# Coluna 'analise_conitec' — parecer técnico do CONITEC
col_analise = [
    "Desfavorável incorporação",
    "Desfavorável incorporação",
    "Desfavorável incorporação",
    "Favorável aprovação",
    "Favorável aprovação",
    "Favorável aprovação",
    "Favorável incorporação",
    "Favorável incorporação",
    "Favorável incorporação",
]

# Coluna 'decisao_ms' — decisão final do Ministério da Saúde
col_decisao = [
    "Não incorporação",
    "Não incorporação",
    "Não incorporação",
    "Não aprovação",
    "Aprovação atualização",
    "Aprovação",
    "Incorporação",
    "Incorporação",
    "Incorporação",
]

# Nomes das colunas numéricas — representam as variáveis epidemiológicas
col_variaveis = [
    "mortalidade covid19 sars pneumonia septicemia",
    "mortalidade covid19 sars pneumonia septicemia",  # repetido pelo peso no dataset
]

# ── MONTAGEM DO CORPUS ────────────────────────────────────────
# Junta todos os textos em um único string para a nuvem geral
corpus_geral = " ".join(
    col_tipo + col_tecnologia + col_demandante +
    col_analise + col_decisao + col_variaveis
)

# Corpus só com texto das decisões CONITEC (tecnologia + análise + decisão)
corpus_conitec = " ".join(col_tecnologia + col_analise + col_decisao + col_demandante)

# Corpus só com termos epidemiológicos
corpus_epi = " ".join(
    col_tipo + col_variaveis +
    ["Covid-19 SARS pandemia mortalidade pneumonia septicemia"] * 3
)

# ── STOPWORDS EM PORTUGUÊS ────────────────────────────────────
# Palavras sem valor semântico que serão ignoradas na nuvem
stopwords_pt = {
    # Preposições e artigos
    'de','da','do','das','dos','para','com','em','e','a','o','que',
    'na','no','por','um','uma','se','sua','seu','suas','seus','ao',
    'aos','às','os','as','nos','nas','à','sob','pelo','pela','pelos',
    'pelas','entre','ou','também','já','ser','ter','como','neste',
    'desta','nessa','desse','desta','este','essa','esse','esta',
    # Palavras funcionais específicas do CSV
    'não','capítulo','incompletos','faixa','etária','indivíduos',
    'solicitação','atualização','publicada','nº','ativa',
    'apresentam','aumentado','progressão','requerem','suplementar',
    'infectados','necessidade','alto','meses','anos','ativo',
    # Números e abreviações
    '2','3','5','6','19','2021','2022','2020','gm','ms','sctie',
}

# ── CÔMPUTO DAS FREQUÊNCIAS ───────────────────────────────────
def contar_palavras(texto, stopwords):
    """Tokeniza o texto e conta frequência de cada palavra relevante."""
    palavras = re.findall(r"[A-Za-zÀ-ÿ\-]{3,}", texto)  # mín. 3 caracteres
    palavras = [p.capitalize() for p in palavras if p.lower() not in stopwords]
    return Counter(palavras)

freq_geral   = contar_palavras(corpus_geral,   stopwords_pt)
freq_conitec = contar_palavras(corpus_conitec, stopwords_pt)
freq_epi     = contar_palavras(corpus_epi,     stopwords_pt)

# ── FUNÇÕES DE COR ────────────────────────────────────────────
def cor_geral(word, font_size, position, orientation, random_state=None, **kwargs):
    """Cores por categoria semântica."""
    doencas   = {'covid-19','sars','sars-cov-2','pneumonia','septicemia',
                 'pandemia','insuficiência','refratária','invasiva'}
    positivos = {'incorporação','aprovação','favorável','vacina','pfizer',
                 'biontech','imunização','prevenção'}
    negativos = {'desfavorável','mortalidade','óbito','grave','septicemia'}
    farmacos  = {'ecmo','remdesivir','nirmatrelvir','ritonavir',
                 'casirivimabe','imdevimabe','tocilizumabe'}
    sistema   = {'conitec','ministro','saúde','secretaria','vigilância',
                 'ciência','tecnologia','inovação','gilead','regulatoria',
                 'regulação','diretrizes','brasileiras'}
    w = word.lower()
    if w in doencas:   return '#e74c3c'   # vermelho — doenças
    if w in positivos: return '#1d9e75'   # verde — positivo
    if w in negativos: return '#922b21'   # vinho — mortalidade
    if w in farmacos:  return '#7d3c98'   # roxo — fármacos
    if w in sistema:   return '#1a6fa8'   # azul — sistema de saúde
    rng = random_state.randint(185, 225) if random_state else 210
    return f'hsl({rng}, 62%, 42%)'

def cor_conitec(word, font_size, position, orientation, random_state=None, **kwargs):
    positivos = {'incorporação','aprovação','favorável','vacina','pfizer',
                 'imunização','biontech','prevenção'}
    negativos = {'desfavorável','não'}
    w = word.lower()
    if w in positivos: return '#1d9e75'
    if w in negativos: return '#c0392b'
    rng = random_state.randint(190, 240) if random_state else 215
    return f'hsl({rng}, 65%, 40%)'

def cor_epi(word, font_size, position, orientation, random_state=None, **kwargs):
    rng   = random_state.randint(0, 35)  if random_state else 10
    light = random_state.randint(33, 52) if random_state else 40
    return f'hsl({rng}, 82%, {light}%)'

# ── GERAÇÃO DAS NUVENS ────────────────────────────────────────
CFG = dict(
    background_color = 'white',
    max_words        = 100,
    prefer_horizontal= 0.72,
    min_font_size    = 10,
    max_font_size    = 95,
    collocations     = False,  # evita bigramas duplicados
    random_state     = 42,     # reprodutibilidade
)

nuvem_geral   = WordCloud(**CFG, width=1400, height=580,
                           color_func=cor_geral).generate_from_frequencies(freq_geral)

nuvem_conitec = WordCloud(**CFG, width=700,  height=400,
                           color_func=cor_conitec).generate_from_frequencies(freq_conitec)

nuvem_epi     = WordCloud(**CFG, width=700,  height=400,
                           color_func=cor_epi).generate_from_frequencies(freq_epi)

# ── LAYOUT DA FIGURA ──────────────────────────────────────────
plt.rcParams.update({'figure.dpi': 130})

fig = plt.figure(figsize=(20, 13))
gs  = gridspec.GridSpec(2, 2, figure=fig,
                         hspace=0.10, wspace=0.04,
                         height_ratios=[1.1, 1])

ax1 = fig.add_subplot(gs[0, :])   # nuvem geral — linha inteira
ax2 = fig.add_subplot(gs[1, 0])  # nuvem CONITEC
ax3 = fig.add_subplot(gs[1, 1])  # nuvem epidemiológica

# ── NUVEM 1: todos os termos do CSV ───────────────────────────
ax1.imshow(nuvem_geral, interpolation='bilinear')
ax1.axis('off')
ax1.set_title(
    'Nuvem de Palavras — obito_tecnologias_unificado.csv (todos os termos)',
    fontsize=14, fontweight='bold', pad=12
)
legenda = [
    Patch(color='#e74c3c', label='Doenças / Condições clínicas'),
    Patch(color='#1d9e75', label='Decisões positivas'),
    Patch(color='#922b21', label='Mortalidade'),
    Patch(color='#7d3c98', label='Fármacos avaliados'),
    Patch(color='#1a6fa8', label='Sistema de saúde / Regulação'),
]
ax1.legend(handles=legenda, loc='lower right', fontsize=9,
           framealpha=0.75, ncol=5, bbox_to_anchor=(1.0, -0.04))

# ── NUVEM 2: termos das decisões CONITEC ─────────────────────
ax2.imshow(nuvem_conitec, interpolation='bilinear')
ax2.axis('off')
ax2.set_title(
    'Termos das Decisões CONITEC (2021–2022)',
    fontsize=12, fontweight='bold', pad=10
)

# ── NUVEM 3: termos epidemiológicos e de mortalidade ─────────
ax3.imshow(nuvem_epi, interpolation='bilinear')
ax3.axis('off')
ax3.set_title(
    'Termos Epidemiológicos — Mortalidade (2020)',
    fontsize=12, fontweight='bold', pad=10
)

# ── RODAPÉ ────────────────────────────────────────────────────
fig.text(
    0.5, 0.005,
    'Fonte: obito_tecnologias_unificado.csv  |  '
    'Frequência baseada no texto real das colunas: tecnologia, demandante, analise_conitec, decisao_ms, tipo',
    ha='center', fontsize=8.5, color='gray'
)

plt.savefig('nuvem_csv_real.png', dpi=150, bbox_inches='tight')
plt.show()

# ── RESUMO ────────────────────────────────────────────────────
print('\n✅ Nuvem salva como nuvem_csv_real.png')
print('\nTop 15 palavras mais frequentes no CSV:')
top15 = freq_geral.most_common(15)
for i, (palavra, n) in enumerate(top15, 1):
    barra = '█' * n
    print(f'  {i:>2}. {palavra:<22} {barra} ({n})')

# ============================================================
#  Mineração de Dados
# ============================================================

# Instala a biblioteca de mineração (só na primeira vez)
!pip install mlxtend -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
import warnings
warnings.filterwarnings('ignore')

print("✅ Bibliotecas carregadas!")

# ═══════════════════════════════════════════════════════════
#  CONCEITOS — o que cada métrica significa:
#
#  SUPORTE    = frequência do itemset no total de transações
#               Suporte(A) = n(A) / n_total
#               Ex: 0.33 → item aparece em 33% das transações
#
#  CONFIANÇA  = probabilidade condicional: P(B | A)
#               Conf(A→B) = Suporte(A∪B) / Suporte(A)
#               Ex: 1.0 → sempre que A ocorre, B também ocorre
#
#  LIFT       = mede se A e B ocorrem juntos mais do que ao acaso
#               Lift(A→B) = Conf(A→B) / Suporte(B)
#               Lift > 1 → associação positiva (não aleatória)
#               Lift = 1 → independência
#               Lift < 1 → associação negativa
# ═══════════════════════════════════════════════════════════

# ── BLOCO 1: TRANSAÇÕES DO CONITEC ───────────────────────────
# Fonte: colunas tecnologia, demandante, analise_conitec, decisao_ms


conitec_trans = [
    # [tipo_tecnologia,  demandante,        analise_conitec,   decisao_ms      ]
    ['Dispositivo',  'Ministro_Saude',  'Desfavoravel',    'Nao_incorporacao'],   # ECMO
    ['Medicamento',  'Gilead',          'Desfavoravel',    'Nao_incorporacao'],   # Remdesivir
    ['Medicamento',  'Secretaria',      'Desfavoravel',    'Nao_incorporacao'],   # Casirivimabe
    ['Diretriz',     'Ministro_Saude',  'Fav_aprovacao',   'Nao_aprovacao'],      # Dir. Ambulatorial
    ['Diretriz',     'Ministro_Saude',  'Fav_aprovacao',   'Aprov_condicional'],  # Dir. Hosp. Cap.2
    ['Diretriz',     'Ministro_Saude',  'Fav_aprovacao',   'Aprovacao'],          # Dir. Hosp. Cap.3
    ['Medicamento',  'Secretaria',      'Fav_incorporacao','Incorporacao'],        # Nirmatrelvir
    ['Medicamento',  'Ministro_Saude',  'Fav_incorporacao','Incorporacao'],        # Tocilizumabe
    ['Vacina',       'Secretaria',      'Fav_incorporacao','Incorporacao'],        # Vacina Pfizer
]

# Rótulos descritivos para exibição
rotulos_conitec = [
    'ECMO', 'Remdesivir', 'Casirivimabe',
    'Dir. Ambulatorial', 'Dir. Hosp. Cap.2', 'Dir. Hosp. Cap.3',
    'Nirmatrelvir', 'Tocilizumabe', 'Vacina Pfizer',
]

# ── BLOCO 2: TRANSAÇÕES DE MORTALIDADE (DISCRETIZADAS) ───────
# Dados numéricos convertidos em categorias para o Aprimoramento
#
# Critério de discretização dos incrementos mensais:
#   COVID  : BAIXO < 100k  |  MÉDIO 100k–500k  |  ALTO > 500k registros/mês
#   SARS   : BAIXO < 10k   |  MÉDIO 10k–80k    |  ALTO > 80k  registros/mês
#   EXCESSO: COM_EXCESSO se óbitos_2020 > óbitos_2019 naquele mês

mort_trans = [
    # [semestre,        covid_nivel,    sars_nivel,   excesso_mortalidade]
    ['PRIMEIRO_SEM', 'COVID_BAIXO',  'SARS_BAIXO',  'SEM_EXCESSO'],  # Jan — início pandemia
    ['PRIMEIRO_SEM', 'COVID_BAIXO',  'SARS_BAIXO',  'COM_EXCESSO'],  # Fev
    ['PRIMEIRO_SEM', 'COVID_BAIXO',  'SARS_BAIXO',  'COM_EXCESSO'],  # Mar
    ['PRIMEIRO_SEM', 'COVID_MEDIO',  'SARS_MEDIO',  'COM_EXCESSO'],  # Abr
    ['PRIMEIRO_SEM', 'COVID_ALTO',   'SARS_ALTO',   'COM_EXCESSO'],  # Mai — 1ª onda
    ['PRIMEIRO_SEM', 'COVID_ALTO',   'SARS_ALTO',   'COM_EXCESSO'],  # Jun
    ['SEGUNDO_SEM',  'COVID_ALTO',   'SARS_ALTO',   'COM_EXCESSO'],  # Jul
    ['SEGUNDO_SEM',  'COVID_ALTO',   'SARS_MEDIO',  'COM_EXCESSO'],  # Ago
    ['SEGUNDO_SEM',  'COVID_ALTO',   'SARS_BAIXO',  'COM_EXCESSO'],  # Set
    ['SEGUNDO_SEM',  'COVID_ALTO',   'SARS_MEDIO',  'COM_EXCESSO'],  # Out
    ['SEGUNDO_SEM',  'COVID_MEDIO',  'SARS_BAIXO',  'COM_EXCESSO'],  # Nov
    ['SEGUNDO_SEM',  'COVID_ALTO',   'SARS_MEDIO',  'SEM_EXCESSO'],  # Dez — início 2ª onda
]

meses_label = ['Jan','Fev','Mar','Abr','Mai','Jun',
               'Jul','Ago','Set','Out','Nov','Dez']

# ── BLOCO 3: CODIFICAÇÃO ONE-HOT (para o Apriori) ────────────


def encode_transacoes(transacoes):
    te = TransactionEncoder()
    array = te.fit(transacoes).transform(transacoes)
    return pd.DataFrame(array, columns=te.columns_)

df_conitec = encode_transacoes(conitec_trans)
df_mort    = encode_transacoes(mort_trans)

print(f"\n📦 Transações CONITEC   : {df_conitec.shape[0]} linhas × {df_conitec.shape[1]} itens")
print(f"📦 Transações Mortality : {df_mort.shape[0]} linhas × {df_mort.shape[1]} itens")

# ── BLOCO 4: ALGORITMO APRIORI ────────────────────────────────
# Gera itemsets frequentes com suporte mínimo definido pelo
# tamanho do dataset (regra prática: min 2 ocorrências)

freq_conitec = apriori(df_conitec, min_support=0.22,   # 2/9 transações
                        use_colnames=True, max_len=3)

freq_mort    = apriori(df_mort,    min_support=0.25,   # 3/12 transações
                        use_colnames=True, max_len=3)

# ── BLOCO 5: EXTRAÇÃO DE REGRAS DE ASSOCIAÇÃO ─────────────────
# min_threshold=0.6 → só regras com confiança ≥ 60%

def gerar_regras(freq_items, min_conf=0.6):
    try:
        # mlxtend >= 0.21 exige num_itemsets
        return association_rules(freq_items, metric='confidence',
                                 min_threshold=min_conf,
                                 num_itemsets=len(freq_items))
    except TypeError:
        return association_rules(freq_items, metric='confidence',
                                 min_threshold=min_conf)

regras_conitec = gerar_regras(freq_conitec).sort_values('lift', ascending=False).reset_index(drop=True)
regras_mort    = gerar_regras(freq_mort).sort_values('lift', ascending=False).reset_index(drop=True)

print(f"\n📋 Regras geradas — CONITEC    : {len(regras_conitec)}")
print(f"📋 Regras geradas — Mortalidade: {len(regras_mort)}")

# ── BLOCO 6: PREPARA TABELAS FORMATADAS ───────────────────────
def formatar_tabela(df, top=8):
    df = df.copy()
    df['Antecedente'] = df['antecedents'].apply(lambda x: ' + '.join(sorted(x)))
    df['Consequente'] = df['consequents'].apply(lambda x: ' + '.join(sorted(x)))
    df['Suporte']     = df['support'].round(3)
    df['Confiança']   = df['confidence'].round(3)
    df['Lift']        = df['lift'].round(2)
    return df[['Antecedente','Consequente','Suporte','Confiança','Lift']].head(top)

tab_conitec = formatar_tabela(regras_conitec)
tab_mort    = formatar_tabela(regras_mort)

# ── BLOCO 7: VISUALIZAÇÃO ─────────────────────────────────────
plt.rcParams.update({'font.family': 'DejaVu Sans', 'figure.dpi': 130})

fig = plt.figure(figsize=(22, 18))
gs  = gridspec.GridSpec(3, 2, figure=fig,
                         height_ratios=[0.55, 1, 1],
                         hspace=0.55, wspace=0.35)

# Legenda de conceitos no topo (linha 0 inteira)
ax_legenda = fig.add_subplot(gs[0, :])
ax_legenda.axis('off')
texto_conceitos = (
    "  SUPORTE = frequência do itemset nas transações  |  "
    "CONFIANÇA = P(B|A): prob. de B dado A  |  "
    "LIFT > 1 = associação real (não aleatória)  |  "
    "Lift = Confiança / Suporte(B)"
)
ax_legenda.text(0.5, 0.6, texto_conceitos, ha='center', va='center',
                fontsize=11, color='white',
                bbox=dict(boxstyle='round,pad=0.6', facecolor='#2c3e50', alpha=0.9))
ax_legenda.set_title(
    'Mineração de Dados — Apriori: obito_tecnologias_unificado.csv',
    fontsize=15, fontweight='bold', pad=8
)

# Eixos dos gráficos
ax1 = fig.add_subplot(gs[1, 0])   # scatter CONITEC
ax2 = fig.add_subplot(gs[1, 1])   # scatter Mortalidade
ax3 = fig.add_subplot(gs[2, 0])   # tabela CONITEC
ax4 = fig.add_subplot(gs[2, 1])   # tabela Mortalidade

# ── Scatter 1: CONITEC ────────────────────────────────────────
# Cada ponto = uma regra; cor = lift; tamanho = confiança
sc1 = ax1.scatter(
    regras_conitec['support'],
    regras_conitec['confidence'],
    c=regras_conitec['lift'],
    cmap='RdYlGn', s=regras_conitec['confidence'] * 300,
    alpha=0.80, edgecolors='#555', linewidth=0.5, zorder=3
)
plt.colorbar(sc1, ax=ax1, label='Lift', shrink=0.85)
ax1.axhline(0.8, color='gray', linestyle='--', alpha=0.5, linewidth=1)
ax1.axvline(0.3, color='gray', linestyle='--', alpha=0.5, linewidth=1)
ax1.set_xlabel('Suporte',    fontsize=10)
ax1.set_ylabel('Confiança',  fontsize=10)
ax1.set_title('Regras de Associação — CONITEC\n(tamanho ∝ confiança | cor = lift)',
              fontweight='bold')
ax1.set_xlim(0, 0.8); ax1.set_ylim(0.5, 1.08)
ax1.grid(True, alpha=0.3)
# Anota as 4 regras com maior lift
for _, row in regras_conitec.head(4).iterrows():
    lbl = ' + '.join(sorted(row['antecedents']))
    ax1.annotate(lbl, (row['support'], row['confidence']),
                 textcoords='offset points', xytext=(6, 3),
                 fontsize=6.5, color='#1a252f', alpha=0.85)

# ── Scatter 2: Mortalidade ────────────────────────────────────
sc2 = ax2.scatter(
    regras_mort['support'],
    regras_mort['confidence'],
    c=regras_mort['lift'],
    cmap='RdYlGn', s=regras_mort['confidence'] * 300,
    alpha=0.80, edgecolors='#555', linewidth=0.5, zorder=3
)
plt.colorbar(sc2, ax=ax2, label='Lift', shrink=0.85)
ax2.axhline(0.8, color='gray', linestyle='--', alpha=0.5, linewidth=1)
ax2.axvline(0.3, color='gray', linestyle='--', alpha=0.5, linewidth=1)
ax2.set_xlabel('Suporte',   fontsize=10)
ax2.set_ylabel('Confiança', fontsize=10)
ax2.set_title('Regras de Associação — Mortalidade (2020)\n(tamanho ∝ confiança | cor = lift)',
              fontweight='bold')
ax2.set_xlim(0, 1.05); ax2.set_ylim(0.5, 1.08)
ax2.grid(True, alpha=0.3)
for _, row in regras_mort.head(4).iterrows():
    lbl = ' + '.join(sorted(row['antecedents']))
    ax2.annotate(lbl, (row['support'], row['confidence']),
                 textcoords='offset points', xytext=(6, 3),
                 fontsize=6.5, color='#1a252f', alpha=0.85)

# ── Tabela 1: Top regras CONITEC ──────────────────────────────
ax3.axis('off')
dados3 = tab_conitec.values.tolist()
colunas3 = list(tab_conitec.columns)
tbl3 = ax3.table(cellText=dados3, colLabels=colunas3,
                  cellLoc='center', loc='center', bbox=[0, 0, 1, 1])
tbl3.auto_set_font_size(False)
tbl3.set_fontsize(8)
for (r, c), cell in tbl3.get_celld().items():
    cell.set_edgecolor('#cccccc')
    if r == 0:                       # cabeçalho
        cell.set_facecolor('#2471a3')
        cell.set_text_props(color='white', fontweight='bold')
    elif r % 2 == 0:                 # linhas pares
        cell.set_facecolor('#eaf4fb')
    else:
        cell.set_facecolor('#ffffff')
# Destaca linhas com confiança = 1.0 (regras perfeitas)
for i, row in enumerate(tab_conitec.itertuples(), start=1):
    if row.Confiança == 1.0:
        for c in range(len(colunas3)):
            tbl3[i, c].set_facecolor('#d5f5e3')
ax3.set_title('Top Regras — CONITEC  (🟢 confiança = 100%)',
              fontweight='bold', fontsize=10, pad=10)

# ── Tabela 2: Top regras Mortalidade ──────────────────────────
ax4.axis('off')
dados4 = tab_mort.values.tolist()
colunas4 = list(tab_mort.columns)
tbl4 = ax4.table(cellText=dados4, colLabels=colunas4,
                  cellLoc='center', loc='center', bbox=[0, 0, 1, 1])
tbl4.auto_set_font_size(False)
tbl4.set_fontsize(8)
for (r, c), cell in tbl4.get_celld().items():
    cell.set_edgecolor('#cccccc')
    if r == 0:
        cell.set_facecolor('#c0392b')
        cell.set_text_props(color='white', fontweight='bold')
    elif r % 2 == 0:
        cell.set_facecolor('#fdedec')
    else:
        cell.set_facecolor('#ffffff')
for i, row in enumerate(tab_mort.itertuples(), start=1):
    if row.Confiança == 1.0:
        for c in range(len(colunas4)):
            tbl4[i, c].set_facecolor('#d5f5e3')
ax4.set_title('Top Regras — Mortalidade (🟢 confiança = 100%)',
              fontweight='bold', fontsize=10, pad=10)

plt.savefig('mineracao_apriori.png', dpi=150, bbox_inches='tight')
plt.show()

# ── BLOCO 8: RESUMO INTERPRETATIVO ───────────────────────────
print("\n" + "="*68)
print("  INTERPRETAÇÃO DAS PRINCIPAIS REGRAS ENCONTRADAS")
print("="*68)

print("\n📌 CONITEC — Top 5 regras por Lift:")
print(f"  {'Antecedente':<30} {'→ Consequente':<28} Sup   Conf  Lift")
print("  " + "-"*62)
for _, row in regras_conitec.head(5).iterrows():
    ant = ' + '.join(sorted(row['antecedents']))
    con = ' + '.join(sorted(row['consequents']))
    print(f"  {ant:<30} → {con:<26} {row['support']:.2f}  {row['confidence']:.2f}  {row['lift']:.2f}")

print("\n📌 Mortalidade 2020 — Top 5 regras por Lift:")
print(f"  {'Antecedente':<32} {'→ Consequente':<22} Sup   Conf  Lift")
print("  " + "-"*62)
for _, row in regras_mort.head(5).iterrows():
    ant = ' + '.join(sorted(row['antecedents']))
    con = ' + '.join(sorted(row['consequents']))
    print(f"  {ant:<32} → {con:<22} {row['support']:.2f}  {row['confidence']:.2f}  {row['lift']:.2f}")

print("\n💡 Leitura das regras:")
print("  • Desfavoravel → Nao_incorporacao  (Conf=1.0, Lift=3.0)")
print("    Sempre que o CONITEC foi desfavorável, o MS não incorporou.")
print("  • Diretriz → Fav_aprovacao         (Conf=1.0, Lift=3.0)")
print("    Todas as diretrizes receberam parecer favorável à aprovação.")
print("  • SARS_BAIXO + PRIMEIRO_SEM → COVID_BAIXO (Conf=1.0, Lift=4.0)")
print("    No 1º sem. com SARS baixo, o COVID também estava baixo (jan-mar).")

print(f"\n✅ Gráfico salvo como mineracao_apriori.png")
print(f"   Total de regras — CONITEC: {len(regras_conitec)} | Mortalidade: {len(regras_mort)}")

# ============================================================
#  ANÁLISE DE ÓBITOS COM IA (GEMINI) — VERSÃO ANTI-BLOQUEIO
# ============================================================

import time #time é um módulo nativo usado para lidar com funções relacionadas ao tempo, como medir a execução de códigos e pausar o sistema.
import logging #logging é a ferramenta ideal para rastrear eventos, registrar erros e depurar códigos de forma profissional.
import google.generativeai as genai #utilização da ia

# 1. Silenciando os avisos vermelhos do servidor (Tornado)
logging.getLogger("tornado.access").setLevel(logging.CRITICAL)

# 2. Configuração da API
API_KEY = "" #colocar-uma-chave-api
genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")
print("✅ Conectado ao Gemini 2.5 Flash! Analisando os dados...\n")

# 3. Inserindo os Dados
DADOS_MORTALIDADE = [
    {"date": "2020-01-01", "covid19": 52, "sars": 1884, "pneumonia": 288523, "septicemia": 235258, "total_2020": 24654, "total_2019": 24718},
    {"date": "2020-02-01", "covid19": 264, "sars": 4588, "pneumonia": 755567, "septicemia": 634915, "total_2020": 47461, "total_2019": 46457},
    {"date": "2020-03-01", "covid19": 4302, "sars": 10134, "pneumonia": 1362963, "septicemia": 1126913, "total_2020": 73864, "total_2019": 70868},
    {"date": "2020-04-01", "covid19": 135633, "sars": 48745, "pneumonia": 1853671, "septicemia": 1505340, "total_2020": 100855, "total_2019": 95052},
    {"date": "2020-05-01", "covid19": 770996, "sars": 186193, "pneumonia": 2397798, "septicemia": 1947896, "total_2020": 133009, "total_2019": 121655},
    {"date": "2020-06-01", "covid19": 1594603, "sars": 270050, "pneumonia": 2744603, "septicemia": 2260780, "total_2020": 165255, "total_2019": 149968},
    {"date": "2020-07-01", "covid19": 2515230, "sars": 332233, "pneumonia": 3253605, "septicemia": 2724403, "total_2020": 198563, "total_2019": 179005},
    {"date": "2020-08-01", "covid19": 3401442, "sars": 377130, "pneumonia": 3677718, "septicemia": 3130029, "total_2020": 231018, "total_2019": 205814},
    {"date": "2020-09-01", "covid19": 3967182, "sars": 399498, "pneumonia": 3977776, "septicemia": 3428684, "total_2020": 259950, "total_2019": 231154},
    {"date": "2020-10-01", "covid19": 4619349, "sars": 440946, "pneumonia": 4565797, "septicemia": 3982430, "total_2020": 289334, "total_2019": 256110},
    {"date": "2020-11-01", "covid19": 4860641, "sars": 449490, "pneumonia": 4834090, "septicemia": 4266933, "total_2020": 315825, "total_2019": 279392},
    {"date": "2020-12-01", "covid19": 5608993, "sars": 492079, "pneumonia": 5399674, "septicemia": 4810979, "total_2020": 338702, "total_2019": 304156},
]

DADOS_REGULATORIOS = [
    {"date": "2021-06-25", "tecnologia": "Oxigenação Extracorpórea (ECMO)", "analise": "Desfavorável à incorporação", "decisao": "Não incorporação"},
    {"date": "2021-09-09", "tecnologia": "Rendesivir para tratamento", "analise": "Desfavorável à incorporação", "decisao": "Não incorporação"},
    {"date": "2022-01-03", "tecnologia": "Casirivimabe/imdevimabe", "analise": "Desfavorável à incorporação", "decisao": "Não incorporação"},
    {"date": "2022-01-26", "tecnologia": "Diretrizes Brasileiras Medicamentoso", "analise": "Favorável à aprovação", "decisao": "Não aprovação"},
    {"date": "2022-01-26", "tecnologia": "Diretrizes Brasileiras Hospitalar", "analise": "Favorável à aprovação", "decisao": "Aprovação com solicitação"},
    {"date": "2022-01-26", "tecnologia": "Diretrizes Brasileiras Dor/Sedação", "analise": "Favorável à aprovação", "decisao": "Aprovação"},
    {"date": "2022-05-06", "tecnologia": "Nirmatrelvir + ritonavir", "analise": "Favorável à incorporação", "decisao": "Incorporação"},
    {"date": "2022-09-12", "tecnologia": "Tocilizumabe", "analise": "Favorável à incorporação", "decisao": "Incorporação"},
    {"date": "2022-12-29", "tecnologia": "Vacina Pfizer/BioNTech", "analise": "Favorável à incorporação", "decisao": "Incorporação"},
]

def montar_contexto():
    linhas = ["=== MORTALIDADE MENSAL 2020 ===", "ATENÇÃO: covid19, sars, pneumonia e septicemia são ACUMULADOS.", ""]
    for r in DADOS_MORTALIDADE:
        linhas.append(f"Mês {r['date']}: covid19_acum={r['covid19']:,} | srag_acum={r['sars']:,} | pneumonia_acum={r['pneumonia']:,} | total_2020={r['total_2020']:,}")
    linhas.append("\n=== DECISÕES REGULATÓRIAS CONITEC ===")
    for r in DADOS_REGULATORIOS:
        linhas.append(f"Data: {r['date']} | Tecnologia: {r['tecnologia']} | Decisão MS: {r['decisao']}")
    return "\n".join(linhas)

CONTEXTO = montar_contexto()

def perguntar_ia(pergunta: str):
    prompt = f"Dados:\n{CONTEXTO}\n\nREGRAS:\n- Responda SEMPRE com base exclusivamente nos dados acima.\n- Seja objetivo.\n\nPergunta: {pergunta}"

    max_tentativas = 3
    for tentativa in range(max_tentativas):
        try:
            response = model.generate_content(prompt)
            print(f"❓ Pergunta: {pergunta}\n" + "─"*65 + f"\n🤖 Resposta:\n{response.text}\n" + "═"*65 + "\n")
            break # Sucesso! Sai do laço de repetição.

        except Exception as e:
            erro = str(e)
            if "429" in erro or "503" in erro:
                print(f"⏳ Limite de velocidade do servidor atingido. Aguardando 15 segundos antes de tentar de novo...")
                time.sleep(15)
            else:
                print(f"❌ Erro: {e}")
                break

# 4. Execução Automática das Perguntas
print("═"*65 + "\n  INICIANDO ANÁLISE AUTOMÁTICA\n" + "═"*65 + "\n")
perguntas = [
    "Qual foi o total acumulado de mortes por COVID-19 até dezembro de 2020?",
    "Quantas pessoas morreram de COVID-19 somente no mês de abril de 2020? (Lembre-se de subtrair do acumulado de março)",
    "Qual foi o mês com maior número de óbitos totais em 2020?",
    "Quais tecnologias foram incorporadas pelo SUS segundo as decisões do MS?"
]

for p in perguntas:
    perguntar_ia(p)
    # Pausa estendida de 12 segundos entre CADA pergunta para respeitar o limite grátis do Google
    time.sleep(12)